// Localhost 
GET http://localhost:3000
###

GET http://localhost:3000/contacts
###

GET http://localhost:3000/contacts/63c2e73112b5e6e43f645ea0
###

// Render Deployment
GET https://travisstirling-02-personal.onrender.com
###

GET https://travisstirling-02-personal.onrender.com/contacts/
###

GET https://travisstirling-02-personal.onrender.com/contacts/63c2e73112b5e6e43f645ea0
###