################### REST variables #######################

// GET, PUT, and DELETE requests utilize @id variable for 
// testing. Paste "Test" document id from database here. 
// If "Test" document does not exist Send POST request first 
@id = 63e898f52cbf25f292878efe

###################### LOCALHOST #########################

// Localhost GET requests 
GET http://localhost:3000 HTTP/1.1 
###

GET http://localhost:3000/photos HTTP/1.1 
###

GET http://localhost:3000/photos/{{id}} HTTP/1.1 
###

// Localhost POST requests 
POST http://localhost:3000/photos HTTP/1.1 
content-type: application/json

{
    "title": "Test Title",
    "photographer": "Test Photographer",
    "description": "Test Description",
    "location": "Test Location",
    "publishDate": "Test Date",
    "fileName": "Test File Name",
    "filePath": "Test File Path"
}
###

// Localhost PUT requests 
PUT http://localhost:3000/photos/{{id}} HTTP/1.1 
content-type: application/json

{
    "title": "The Art of War",
    "photographer": "Muhammad Ali",
    "description": "Ali's Rumble in the Jungle",
    "location": "Africa",
    "publishDate": "02/11/2023",
    "fileName": "ali-rumble.png",
    "filePath": "/photos/ali-rumble.png"
}
###

// Localhost DELETE requests 
DELETE http://localhost:3000/photos/{{id}} HTTP/1.1 
###

###################### PRODUCTION #########################

// Render GET requests 
GET https://travisstirling-06-personal.onrender.com HTTP/1.1 
###

GET https://travisstirling-06-personal.onrender.com/photos HTTP/1.1 
###

GET https://travisstirling-06-personal.onrender.com/photos/{{id}} HTTP/1.1 
###

// Render POST requests 
POST https://travisstirling-06-personal.onrender.com/photos HTTP/1.1 
content-type: application/json

{
    "title": "Test Title",
    "photographer": "Test Photographer",
    "description": "Test Description",
    "location": "Test Location",
    "publishDate": "Test Date",
    "fileName": "Test File Name",
    "filePath": "Test File Path"
}
###

// Render PUT requests 
PUT https://travisstirling-06-personal.onrender.com/photos/{{id}} HTTP/1.1 
content-type: application/json

{
    "title": "The Art of War",
    "photographer": "Muhammad Ali",
    "description": "Ali's Rumble in the Jungle",
    "location": "Africa",
    "publishDate": "02/11/2023",
    "fileName": "ali-rumble.png",
    "filePath": "/photos/ali-rumble.png"
}
###

// Render DELETE requests 
DELETE https://travisstirling-06-personal.onrender.com/photos/{{id}} HTTP/1.1 
###