################### REST variables #######################

// GET, PUT, and DELETE requests utilize @id variable for 
// testing. Paste "Test" document id from database here.
// If "Test" document does not exist Send POST request first
@id = 63d5f610b533e669eacaabc2

###################### LOCALHOST #########################

// Localhost GET requests
GET http://localhost:3000 HTTP/1.1
###

GET http://localhost:3000/contacts HTTP/1.1
###

GET http://localhost:3000/contacts/{{id}} HTTP/1.1
###

// Localhost POST requests
POST http://localhost:3000/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Test",
    "lastName": "Test",
    "email": "Test_T@gmail.com",
    "favoriteColor": "white",
    "birthday": "12/34/5678"
}
###

// Localhost PUT requests
PUT http://localhost:3000/contacts/{{id}} HTTP/1.1
content-type: application/json

{
    "firstName": "Test",
    "lastName": "Test",
    "email": "Test_T@gmail.com",
    "favoriteColor": "black",
    "birthday": "12/34/5678"
}
###

// Localhost DELETE requests
DELETE http://localhost:3000/contacts/{{id}} HTTP/1.1
###

###################### PRODUCTION #########################

// Render GET requests
GET https://travisstirling-04-personal.onrender.com HTTP/1.1
###

GET https://travisstirling-04-personal.onrender.com/contacts/ HTTP/1.1
###

GET https://travisstirling-04-personal.onrender.com/contacts/{{id}} HTTP/1.1
###

// Render POST requests
POST https://travisstirling-04-personal.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName": "Test",
    "lastName": "Test",
    "email": "Test_T@gmail.com",
    "favoriteColor": "white",
    "birthday": "12/34/5678"
}
###

// Render PUT requests
PUT https://travisstirling-04-personal.onrender.com/contacts/{{id}} HTTP/1.1
content-type: application/json

{
    "firstName": "Test",
    "lastName": "Test",
    "email": "Test_T@gmail.com",
    "favoriteColor": "black",
    "birthday": "12/34/5678"
}
###

// Render DELETE requests
DELETE https://travisstirling-04-personal.onrender.com/contacts/{{id}} HTTP/1.1
###
